### ISSUE TITLE
Upload tool broken

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-incubator/Galaxy#1]
Relocating tools, including the upload tool, outside the main Galaxy tree seems to have broken the upload tool.  Most likely the upload.py file contains hard coded paths.  See Stephan's modifications to the upload tool for a possible fix.

**Comment by marcverhagen** [comment]
I think I found the problem. Upload works fine when I remove the validator from upload.xml. It was part of the initial import for GalaxyMods, but that must have been from oldish code because the validator was removed in Jan 2016. See https://github.com/lappsgrid-incubator/Galaxy/commit/193c5293d9552d53a2358254fa2a25b236a31511.

**Comment by ksuderman** [comment]
The fix has been merged.
